In [3]:
import os
import numpy as np
from matplotlib.image import imread
from skimage.measure import label, regionprops
from skimage.color import rgb2gray, rgba2rgb

points_path = 'Sample/Clandmarks.png'
image_path = 'Sample/Cim.png'
points_im = imread(points_path)
rgb_im = rgba2rgb(points_im)
im = rgb2gray(rgb_im)
rgb_points = rgba2rgb(points_im)
points = rgb_points[points_im[..., -1] == 1, :]
regions = np.unique(points, axis=0)
for region in regions:
    region_mask = np.prod(
        rgb_im == region.reshape(1, 3), axis=-1
    ).astype(bool)
    label_img = label(region_mask)
    region_props = regionprops(label_img)
    centroids = [prop.centroid for prop in region_props]
    print(region * 255, centroids)

[  0. 144. 217.] [(220.0, 169.0), (231.0, 118.0)]
[ 21.  49. 246.] [(277.0, 100.0), (329.0, 189.0), (330.0, 157.0)]
[ 21. 246.  34.] [(198.0, 217.0), (199.0, 168.0), (225.0, 175.0), (226.0, 217.0)]
[ 98.   0. 217.] [(165.0, 281.0), (190.0, 306.0), (203.0, 226.0), (225.0, 288.0)]
[217.   0. 212.] [(181.0, 137.0), (272.0, 153.0)]
[217.  22.   0.] [(305.0, 237.0), (308.0, 213.0), (318.0, 263.0)]
[217. 117.   0.] [(117.0, 340.0), (141.0, 369.0), (155.0, 313.0), (179.0, 371.0), (188.0, 328.0), (217.0, 378.0), (222.0, 323.0), (252.0, 358.0)]
[255. 211.   0.] [(62.0, 217.0), (164.0, 400.0), (241.0, 49.0), (350.0, 231.0)]
